package in.skaipal.kushalm.cuisinicuser.model;

public class APIUrls {
    public static String API_VERSION = "webservices/";
    public static String BASE_URL = "http://cuisinic.in/";
    public static String applyContestUrl;
    public static String bookTableUrl;
    public static String deliveryUrl;
    public static String fcmUrl;
    public static String getContestUrl;
    public static String getItemDetailsUrl;
    public static String getMenuUrl;
    public static String getRecipeUrl;
    public static String liveMusicBookingUrl;
    public static String liveMusicUrl;
    public static String loginUrl;
    public static String offerUrl;
    public static String orderStatusUrl;
    public static String ownSalad;
    public static String shareRecipeUrl;
    public static String signupUrl;
    public static String updateOrderStatusUrl;
    public static String updateProfileUrl;

    static {
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.append(BASE_URL);
        stringBuilder.append(API_VERSION);
        stringBuilder.append("set_user.php");
        signupUrl = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(BASE_URL);
        stringBuilder.append(API_VERSION);
        stringBuilder.append("get_user.php");
        loginUrl = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(BASE_URL);
        stringBuilder.append(API_VERSION);
        stringBuilder.append("share_recipe.php");
        shareRecipeUrl = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(BASE_URL);
        stringBuilder.append(API_VERSION);
        stringBuilder.append("set_order_details.php");
        bookTableUrl = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(BASE_URL);
        stringBuilder.append(API_VERSION);
        stringBuilder.append("get_contest.php");
        getContestUrl = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(BASE_URL);
        stringBuilder.append(API_VERSION);
        stringBuilder.append("get_menu.php");
        getMenuUrl = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(BASE_URL);
        stringBuilder.append(API_VERSION);
        stringBuilder.append("set_order_details.php");
        deliveryUrl = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(BASE_URL);
        stringBuilder.append(API_VERSION);
        stringBuilder.append("get_live_music_details.php");
        liveMusicUrl = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(BASE_URL);
        stringBuilder.append(API_VERSION);
        stringBuilder.append("book_live_music.php");
        liveMusicBookingUrl = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(BASE_URL);
        stringBuilder.append(API_VERSION);
        stringBuilder.append("get_own_salad.php");
        ownSalad = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(BASE_URL);
        stringBuilder.append(API_VERSION);
        stringBuilder.append("update_user.php");
        updateProfileUrl = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(BASE_URL);
        stringBuilder.append(API_VERSION);
        stringBuilder.append("get_sahred_recepies.php");
        getRecipeUrl = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(BASE_URL);
        stringBuilder.append(API_VERSION);
        stringBuilder.append("apply_contest.php");
        applyContestUrl = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(BASE_URL);
        stringBuilder.append(API_VERSION);
        stringBuilder.append("get_order_status.php");
        orderStatusUrl = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(BASE_URL);
        stringBuilder.append(API_VERSION);
        stringBuilder.append("get_item_details.php");
        getItemDetailsUrl = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(BASE_URL);
        stringBuilder.append(API_VERSION);
        stringBuilder.append("update_order_status.php");
        updateOrderStatusUrl = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(BASE_URL);
        stringBuilder.append(API_VERSION);
        stringBuilder.append("update_fcm.php");
        fcmUrl = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(BASE_URL);
        stringBuilder.append(API_VERSION);
        stringBuilder.append("get_offers.php");
        offerUrl = stringBuilder.toString();
    }
}
